### ISSUE TITLE
Virus detected: heur trojan andro idos boogr

### ISSUE THREAD

**Issue by Flashwalker** [axxapy/apkExtractor#26]
When i started banking app of Sberbank it throws me popup with alert about virus found ("heur trojan andro idos boogr)"and button for delete it. When i press the button it throws suggesting to delete Apk extractor.
![Imagepipe_13](https://user-images.githubusercontent.com/2188215/91689602-2270c580-eb6d-11ea-9e3d-fea6ef760fdc.jpg)

**Comment by axxapy** [comment]
false positive.
check source code, it is 100% open.

Sberbank's "antivirus" is as good as their financial services.

I suspect it may be confusing apkExtractor with some virus due to root-related logic.
